### ISSUE TITLE
executing on multi machine report txns 0?

### ISSUE THREAD

**Issue by shijiaxin** [yaledb/calvin#5]
Hi,i am trying the calvin.I use the source code in src_calvin.

I followed  instructions in README and successfully run calvin.
If i run calvin with 1 node (setting 1 node in deploy-run.conf),the program works fine and print roughly 20,000txns/s.
But if a run it with more than 1 node,the statics reported would be all 0.I run each of the seperatelly and it works fine.
I use the following command.
    bin/deployment/cluster -c deploy-run.conf -p src/deployment/portfile -d bin/deployment/db m 0
Can you help me with that?Thanks !

**Comment by yaledb** [comment]
Thanks for you interest.
1. First, you should make sure your deploy-run.conf file is correct, the format for each line is Node id=replica:partition:cores:host:port. If you have 2 partitions, it may look like:
node0=0:0:8:128.36.232.18:51262
node1=0:1:8:128.36.232.12:51261

Note that 0:0 and 0:1 means you have 2 partitions in 1 replica. 

2. While running multiple machines, you should make sure each machine has the same user name and can ssh the other machines without password, like "ssh 128.26.232.18".  Also you need to make sure each machine has the exactly the same code, so if you change the code, you should make sure all machines have the same code, and you should build the same code using make on each machine.

Hope this helps. Let me know if it still doesn't work. Thanks.

**Comment by yaledb** [comment]
Note that, changed MAX_BATCH_SIZE to a bigger number(say 500) in sequencer/sequencer.h, you can get more throughput for micro benchmark. 

Hope this helps. 
Kun Ren (renkun.nwpu@gmail.com)
